# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU


ga_tracking_id: 'UA-25308850-2'


shufti_endpoint: 'https://api.shuftipro.com/'
shufti_client_id: 'b8UdLdiM9FLX1jqhpEPYTALu9GPddCXc6k4cV5mOxHikMwAlu81612327008'
shufti_secret_key: '$2y$10$FP1zShMtO9Uxg83UjAJsVudFvpYwhUN5J2jyYJNI8mfH5Jey5a6p6'


development:
  shufti_callback_url: 'https://c0ffe43ecccf.ngrok.io/callback'
  shufti_redirect_url: 'https://c0ffe43ecccf.ngrok.io/account'


staging:
  shufti_callback_url: 'http://eurofunding-staging.ajkoffshore.com/callback'
  shufti_redirect_url: 'http://eurofunding-staging.ajkoffshore.com/account'


production:
  shufti_callback_url: 'https://www.eurofunding.co.uk/callback'
  shufti_redirect_url: 'https://www.eurofunding.co.uk/account'



